server:
  port: 1112
spring:
  application:
    name: provider-one
eureka:
  client:
        service-url:
          defaultZone: http://localhost:1111/eureka/
        register-with-eureka: true
  instance:
    prefer-ip-address: true

